/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMTaxRouteImport } from './routes/_authenticated/m/tax'
import { Route as AuthenticatedMSalesRouteImport } from './routes/_authenticated/m/sales'
import { Route as AuthenticatedMReportsRouteImport } from './routes/_authenticated/m/reports'
import { Route as AuthenticatedMInventoryRouteImport } from './routes/_authenticated/m/inventory'
import { Route as AuthenticatedMFinanceRouteImport } from './routes/_authenticated/m/finance'
import { Route as AuthenticatedMEmployeesRouteImport } from './routes/_authenticated/m/employees'
import { Route as AuthenticatedMCrmRouteImport } from './routes/_authenticated/m/crm'
import { Route as AuthenticatedMComplianceRouteImport } from './routes/_authenticated/m/compliance'
import { Route as AuthenticatedMBusinessPerformanceRouteImport } from './routes/_authenticated/m/business-performance'
import { Route as AuthenticatedMAdminRouteImport } from './routes/_authenticated/m/admin'
import { Route as AuthenticatedMCrmIndexRouteImport } from './routes/_authenticated/m/crm.index'
import { Route as AuthenticatedMComplianceIndexRouteImport } from './routes/_authenticated/m/compliance.index'
import { Route as AuthenticatedMTaxWithholdingRouteImport } from './routes/_authenticated/m/tax.withholding'
import { Route as AuthenticatedMTaxVatRouteImport } from './routes/_authenticated/m/tax.vat'
import { Route as AuthenticatedMTaxSalesRouteImport } from './routes/_authenticated/m/tax.sales'
import { Route as AuthenticatedMTaxReportsRouteImport } from './routes/_authenticated/m/tax.reports'
import { Route as AuthenticatedMTaxPurchasesRouteImport } from './routes/_authenticated/m/tax.purchases'
import { Route as AuthenticatedMTaxIncomeRouteImport } from './routes/_authenticated/m/tax.income'
import { Route as AuthenticatedMTaxExpensesRouteImport } from './routes/_authenticated/m/tax.expenses'
import { Route as AuthenticatedMTaxDocumentsRouteImport } from './routes/_authenticated/m/tax.documents'
import { Route as AuthenticatedMTaxCalendarRouteImport } from './routes/_authenticated/m/tax.calendar'
import { Route as AuthenticatedMTaxAssetsRouteImport } from './routes/_authenticated/m/tax.assets'
import { Route as AuthenticatedMSalesReturnsRouteImport } from './routes/_authenticated/m/sales.returns'
import { Route as AuthenticatedMSalesReportsRouteImport } from './routes/_authenticated/m/sales.reports'
import { Route as AuthenticatedMSalesQuotationsRouteImport } from './routes/_authenticated/m/sales.quotations'
import { Route as AuthenticatedMSalesPaymentsRouteImport } from './routes/_authenticated/m/sales.payments'
import { Route as AuthenticatedMSalesOrdersRouteImport } from './routes/_authenticated/m/sales.orders'
import { Route as AuthenticatedMSalesNewRouteImport } from './routes/_authenticated/m/sales.new'
import { Route as AuthenticatedMSalesInvoicesRouteImport } from './routes/_authenticated/m/sales.invoices'
import { Route as AuthenticatedMSalesHistoryRouteImport } from './routes/_authenticated/m/sales.history'
import { Route as AuthenticatedMSalesDraftsRouteImport } from './routes/_authenticated/m/sales.drafts'
import { Route as AuthenticatedMInventoryWarehousesRouteImport } from './routes/_authenticated/m/inventory.warehouses'
import { Route as AuthenticatedMInventoryTransfersRouteImport } from './routes/_authenticated/m/inventory.transfers'
import { Route as AuthenticatedMInventorySuppliersRouteImport } from './routes/_authenticated/m/inventory.suppliers'
import { Route as AuthenticatedMInventoryStockRouteImport } from './routes/_authenticated/m/inventory.stock'
import { Route as AuthenticatedMInventoryPurchasesRouteImport } from './routes/_authenticated/m/inventory.purchases'
import { Route as AuthenticatedMInventoryProductsRouteImport } from './routes/_authenticated/m/inventory.products'
import { Route as AuthenticatedMInventoryOverviewRouteImport } from './routes/_authenticated/m/inventory.overview'
import { Route as AuthenticatedMInventoryMovementsRouteImport } from './routes/_authenticated/m/inventory.movements'
import { Route as AuthenticatedMInventoryCategoriesRouteImport } from './routes/_authenticated/m/inventory.categories'
import { Route as AuthenticatedMFinanceTransfersRouteImport } from './routes/_authenticated/m/finance.transfers'
import { Route as AuthenticatedMFinanceReportsRouteImport } from './routes/_authenticated/m/finance.reports'
import { Route as AuthenticatedMFinancePaymentsRouteImport } from './routes/_authenticated/m/finance.payments'
import { Route as AuthenticatedMFinanceExpensesRouteImport } from './routes/_authenticated/m/finance.expenses'
import { Route as AuthenticatedMFinanceAccountsRouteImport } from './routes/_authenticated/m/finance.accounts'
import { Route as AuthenticatedMEmployeesStaffRouteImport } from './routes/_authenticated/m/employees.staff'
import { Route as AuthenticatedMEmployeesRecruitmentRouteImport } from './routes/_authenticated/m/employees.recruitment'
import { Route as AuthenticatedMEmployeesPerformanceRouteImport } from './routes/_authenticated/m/employees.performance'
import { Route as AuthenticatedMEmployeesPayslipsRouteImport } from './routes/_authenticated/m/employees.payslips'
import { Route as AuthenticatedMEmployeesPayrollRouteImport } from './routes/_authenticated/m/employees.payroll'
import { Route as AuthenticatedMEmployeesLeaveRouteImport } from './routes/_authenticated/m/employees.leave'
import { Route as AuthenticatedMEmployeesDepartmentsRouteImport } from './routes/_authenticated/m/employees.departments'
import { Route as AuthenticatedMEmployeesContractsRouteImport } from './routes/_authenticated/m/employees.contracts'
import { Route as AuthenticatedMEmployeesAttendanceRouteImport } from './routes/_authenticated/m/employees.attendance'
import { Route as AuthenticatedMCrmMarketRouteImport } from './routes/_authenticated/m/crm.market'
import { Route as AuthenticatedMCrmCustomersRouteImport } from './routes/_authenticated/m/crm.customers'
import { Route as AuthenticatedMCrmChannelsRouteImport } from './routes/_authenticated/m/crm.channels'
import { Route as AuthenticatedMCrmCampaignsRouteImport } from './routes/_authenticated/m/crm.campaigns'
import { Route as AuthenticatedMCrmAnalyticsRouteImport } from './routes/_authenticated/m/crm.analytics'
import { Route as AuthenticatedMComplianceReportsRouteImport } from './routes/_authenticated/m/compliance.reports'
import { Route as AuthenticatedMComplianceProfileRouteImport } from './routes/_authenticated/m/compliance.profile'
import { Route as AuthenticatedMComplianceLicencesRouteImport } from './routes/_authenticated/m/compliance.licences'
import { Route as AuthenticatedMComplianceCalendarRouteImport } from './routes/_authenticated/m/compliance.calendar'
import { Route as AuthenticatedMAdminUsersRouteImport } from './routes/_authenticated/m/admin.users'
import { Route as AuthenticatedMAdminSettingsRouteImport } from './routes/_authenticated/m/admin.settings'
import { Route as AuthenticatedMAdminSecurityRouteImport } from './routes/_authenticated/m/admin.security'
import { Route as AuthenticatedMAdminRolesRouteImport } from './routes/_authenticated/m/admin.roles'
import { Route as AuthenticatedMAdminActivityLogsRouteImport } from './routes/_authenticated/m/admin.activity-logs'
import { Route as AuthenticatedMCrmCustomersIdRouteImport } from './routes/_authenticated/m/crm.customers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMTaxRoute = AuthenticatedMTaxRouteImport.update({
  id: '/m/tax',
  path: '/m/tax',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMSalesRoute = AuthenticatedMSalesRouteImport.update({
  id: '/m/sales',
  path: '/m/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMReportsRoute = AuthenticatedMReportsRouteImport.update({
  id: '/m/reports',
  path: '/m/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMInventoryRoute = AuthenticatedMInventoryRouteImport.update({
  id: '/m/inventory',
  path: '/m/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMFinanceRoute = AuthenticatedMFinanceRouteImport.update({
  id: '/m/finance',
  path: '/m/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMEmployeesRoute = AuthenticatedMEmployeesRouteImport.update({
  id: '/m/employees',
  path: '/m/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMCrmRoute = AuthenticatedMCrmRouteImport.update({
  id: '/m/crm',
  path: '/m/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMComplianceRoute =
  AuthenticatedMComplianceRouteImport.update({
    id: '/m/compliance',
    path: '/m/compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMBusinessPerformanceRoute =
  AuthenticatedMBusinessPerformanceRouteImport.update({
    id: '/m/business-performance',
    path: '/m/business-performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMAdminRoute = AuthenticatedMAdminRouteImport.update({
  id: '/m/admin',
  path: '/m/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMCrmIndexRoute = AuthenticatedMCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMCrmRoute,
} as any)
const AuthenticatedMComplianceIndexRoute =
  AuthenticatedMComplianceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMComplianceRoute,
  } as any)
const AuthenticatedMTaxWithholdingRoute =
  AuthenticatedMTaxWithholdingRouteImport.update({
    id: '/withholding',
    path: '/withholding',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxVatRoute = AuthenticatedMTaxVatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMTaxSalesRoute = AuthenticatedMTaxSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMTaxReportsRoute =
  AuthenticatedMTaxReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxPurchasesRoute =
  AuthenticatedMTaxPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxIncomeRoute = AuthenticatedMTaxIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMTaxExpensesRoute =
  AuthenticatedMTaxExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxDocumentsRoute =
  AuthenticatedMTaxDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxCalendarRoute =
  AuthenticatedMTaxCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedMTaxRoute,
  } as any)
const AuthenticatedMTaxAssetsRoute = AuthenticatedMTaxAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedMTaxRoute,
} as any)
const AuthenticatedMSalesReturnsRoute =
  AuthenticatedMSalesReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => AuthenticatedMSalesRoute,
  } as any)
const AuthenticatedMSalesReportsRoute =
  AuthenticatedMSalesReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedMSalesRoute,
  } as any)
const AuthenticatedMSalesQuotationsRoute =
  AuthenticatedMSalesQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => AuthenticatedMSalesRoute,
  } as any)
const AuthenticatedMSalesPaymentsRoute =
  AuthenticatedMSalesPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedMSalesRoute,
  } as any)
const AuthenticatedMSalesOrdersRoute =
  AuthenticatedMSalesOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedMSalesRoute,
  } as any)
const AuthenticatedMSalesNewRoute = AuthenticatedMSalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedMSalesRoute,
} as any)
const AuthenticatedMSalesInvoicesRoute =
  AuthenticatedMSalesInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedMSalesRoute,
  } as any)
const AuthenticatedMSalesHistoryRoute =
  AuthenticatedMSalesHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedMSalesRoute,
  } as any)
const AuthenticatedMSalesDraftsRoute =
  AuthenticatedMSalesDraftsRouteImport.update({
    id: '/drafts',
    path: '/drafts',
    getParentRoute: () => AuthenticatedMSalesRoute,
  } as any)
const AuthenticatedMInventoryWarehousesRoute =
  AuthenticatedMInventoryWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMInventoryTransfersRoute =
  AuthenticatedMInventoryTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMInventorySuppliersRoute =
  AuthenticatedMInventorySuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMInventoryStockRoute =
  AuthenticatedMInventoryStockRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMInventoryPurchasesRoute =
  AuthenticatedMInventoryPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMInventoryProductsRoute =
  AuthenticatedMInventoryProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMInventoryOverviewRoute =
  AuthenticatedMInventoryOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMInventoryMovementsRoute =
  AuthenticatedMInventoryMovementsRouteImport.update({
    id: '/movements',
    path: '/movements',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMInventoryCategoriesRoute =
  AuthenticatedMInventoryCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedMInventoryRoute,
  } as any)
const AuthenticatedMFinanceTransfersRoute =
  AuthenticatedMFinanceTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedMFinanceRoute,
  } as any)
const AuthenticatedMFinanceReportsRoute =
  AuthenticatedMFinanceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedMFinanceRoute,
  } as any)
const AuthenticatedMFinancePaymentsRoute =
  AuthenticatedMFinancePaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedMFinanceRoute,
  } as any)
const AuthenticatedMFinanceExpensesRoute =
  AuthenticatedMFinanceExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedMFinanceRoute,
  } as any)
const AuthenticatedMFinanceAccountsRoute =
  AuthenticatedMFinanceAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedMFinanceRoute,
  } as any)
const AuthenticatedMEmployeesStaffRoute =
  AuthenticatedMEmployeesStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMEmployeesRecruitmentRoute =
  AuthenticatedMEmployeesRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMEmployeesPerformanceRoute =
  AuthenticatedMEmployeesPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMEmployeesPayslipsRoute =
  AuthenticatedMEmployeesPayslipsRouteImport.update({
    id: '/payslips',
    path: '/payslips',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMEmployeesPayrollRoute =
  AuthenticatedMEmployeesPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMEmployeesLeaveRoute =
  AuthenticatedMEmployeesLeaveRouteImport.update({
    id: '/leave',
    path: '/leave',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMEmployeesDepartmentsRoute =
  AuthenticatedMEmployeesDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMEmployeesContractsRoute =
  AuthenticatedMEmployeesContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMEmployeesAttendanceRoute =
  AuthenticatedMEmployeesAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedMEmployeesRoute,
  } as any)
const AuthenticatedMCrmMarketRoute = AuthenticatedMCrmMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedMCrmRoute,
} as any)
const AuthenticatedMCrmCustomersRoute =
  AuthenticatedMCrmCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMCrmChannelsRoute =
  AuthenticatedMCrmChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMCrmCampaignsRoute =
  AuthenticatedMCrmCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMCrmAnalyticsRoute =
  AuthenticatedMCrmAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedMCrmRoute,
  } as any)
const AuthenticatedMComplianceReportsRoute =
  AuthenticatedMComplianceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedMComplianceRoute,
  } as any)
const AuthenticatedMComplianceProfileRoute =
  AuthenticatedMComplianceProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedMComplianceRoute,
  } as any)
const AuthenticatedMComplianceLicencesRoute =
  AuthenticatedMComplianceLicencesRouteImport.update({
    id: '/licences',
    path: '/licences',
    getParentRoute: () => AuthenticatedMComplianceRoute,
  } as any)
const AuthenticatedMComplianceCalendarRoute =
  AuthenticatedMComplianceCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedMComplianceRoute,
  } as any)
const AuthenticatedMAdminUsersRoute =
  AuthenticatedMAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedMAdminRoute,
  } as any)
const AuthenticatedMAdminSettingsRoute =
  AuthenticatedMAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMAdminRoute,
  } as any)
const AuthenticatedMAdminSecurityRoute =
  AuthenticatedMAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedMAdminRoute,
  } as any)
const AuthenticatedMAdminRolesRoute =
  AuthenticatedMAdminRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedMAdminRoute,
  } as any)
const AuthenticatedMAdminActivityLogsRoute =
  AuthenticatedMAdminActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedMAdminRoute,
  } as any)
const AuthenticatedMCrmCustomersIdRoute =
  AuthenticatedMCrmCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMCrmCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/m/admin': typeof AuthenticatedMAdminRouteWithChildren
  '/m/business-performance': typeof AuthenticatedMBusinessPerformanceRoute
  '/m/compliance': typeof AuthenticatedMComplianceRouteWithChildren
  '/m/crm': typeof AuthenticatedMCrmRouteWithChildren
  '/m/employees': typeof AuthenticatedMEmployeesRouteWithChildren
  '/m/finance': typeof AuthenticatedMFinanceRouteWithChildren
  '/m/inventory': typeof AuthenticatedMInventoryRouteWithChildren
  '/m/reports': typeof AuthenticatedMReportsRoute
  '/m/sales': typeof AuthenticatedMSalesRouteWithChildren
  '/m/tax': typeof AuthenticatedMTaxRouteWithChildren
  '/m/admin/activity-logs': typeof AuthenticatedMAdminActivityLogsRoute
  '/m/admin/roles': typeof AuthenticatedMAdminRolesRoute
  '/m/admin/security': typeof AuthenticatedMAdminSecurityRoute
  '/m/admin/settings': typeof AuthenticatedMAdminSettingsRoute
  '/m/admin/users': typeof AuthenticatedMAdminUsersRoute
  '/m/compliance/calendar': typeof AuthenticatedMComplianceCalendarRoute
  '/m/compliance/licences': typeof AuthenticatedMComplianceLicencesRoute
  '/m/compliance/profile': typeof AuthenticatedMComplianceProfileRoute
  '/m/compliance/reports': typeof AuthenticatedMComplianceReportsRoute
  '/m/crm/analytics': typeof AuthenticatedMCrmAnalyticsRoute
  '/m/crm/campaigns': typeof AuthenticatedMCrmCampaignsRoute
  '/m/crm/channels': typeof AuthenticatedMCrmChannelsRoute
  '/m/crm/customers': typeof AuthenticatedMCrmCustomersRouteWithChildren
  '/m/crm/market': typeof AuthenticatedMCrmMarketRoute
  '/m/employees/attendance': typeof AuthenticatedMEmployeesAttendanceRoute
  '/m/employees/contracts': typeof AuthenticatedMEmployeesContractsRoute
  '/m/employees/departments': typeof AuthenticatedMEmployeesDepartmentsRoute
  '/m/employees/leave': typeof AuthenticatedMEmployeesLeaveRoute
  '/m/employees/payroll': typeof AuthenticatedMEmployeesPayrollRoute
  '/m/employees/payslips': typeof AuthenticatedMEmployeesPayslipsRoute
  '/m/employees/performance': typeof AuthenticatedMEmployeesPerformanceRoute
  '/m/employees/recruitment': typeof AuthenticatedMEmployeesRecruitmentRoute
  '/m/employees/staff': typeof AuthenticatedMEmployeesStaffRoute
  '/m/finance/accounts': typeof AuthenticatedMFinanceAccountsRoute
  '/m/finance/expenses': typeof AuthenticatedMFinanceExpensesRoute
  '/m/finance/payments': typeof AuthenticatedMFinancePaymentsRoute
  '/m/finance/reports': typeof AuthenticatedMFinanceReportsRoute
  '/m/finance/transfers': typeof AuthenticatedMFinanceTransfersRoute
  '/m/inventory/categories': typeof AuthenticatedMInventoryCategoriesRoute
  '/m/inventory/movements': typeof AuthenticatedMInventoryMovementsRoute
  '/m/inventory/overview': typeof AuthenticatedMInventoryOverviewRoute
  '/m/inventory/products': typeof AuthenticatedMInventoryProductsRoute
  '/m/inventory/purchases': typeof AuthenticatedMInventoryPurchasesRoute
  '/m/inventory/stock': typeof AuthenticatedMInventoryStockRoute
  '/m/inventory/suppliers': typeof AuthenticatedMInventorySuppliersRoute
  '/m/inventory/transfers': typeof AuthenticatedMInventoryTransfersRoute
  '/m/inventory/warehouses': typeof AuthenticatedMInventoryWarehousesRoute
  '/m/sales/drafts': typeof AuthenticatedMSalesDraftsRoute
  '/m/sales/history': typeof AuthenticatedMSalesHistoryRoute
  '/m/sales/invoices': typeof AuthenticatedMSalesInvoicesRoute
  '/m/sales/new': typeof AuthenticatedMSalesNewRoute
  '/m/sales/orders': typeof AuthenticatedMSalesOrdersRoute
  '/m/sales/payments': typeof AuthenticatedMSalesPaymentsRoute
  '/m/sales/quotations': typeof AuthenticatedMSalesQuotationsRoute
  '/m/sales/reports': typeof AuthenticatedMSalesReportsRoute
  '/m/sales/returns': typeof AuthenticatedMSalesReturnsRoute
  '/m/tax/assets': typeof AuthenticatedMTaxAssetsRoute
  '/m/tax/calendar': typeof AuthenticatedMTaxCalendarRoute
  '/m/tax/documents': typeof AuthenticatedMTaxDocumentsRoute
  '/m/tax/expenses': typeof AuthenticatedMTaxExpensesRoute
  '/m/tax/income': typeof AuthenticatedMTaxIncomeRoute
  '/m/tax/purchases': typeof AuthenticatedMTaxPurchasesRoute
  '/m/tax/reports': typeof AuthenticatedMTaxReportsRoute
  '/m/tax/sales': typeof AuthenticatedMTaxSalesRoute
  '/m/tax/vat': typeof AuthenticatedMTaxVatRoute
  '/m/tax/withholding': typeof AuthenticatedMTaxWithholdingRoute
  '/m/compliance/': typeof AuthenticatedMComplianceIndexRoute
  '/m/crm/': typeof AuthenticatedMCrmIndexRoute
  '/m/crm/customers/$id': typeof AuthenticatedMCrmCustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/m/admin': typeof AuthenticatedMAdminRouteWithChildren
  '/m/business-performance': typeof AuthenticatedMBusinessPerformanceRoute
  '/m/employees': typeof AuthenticatedMEmployeesRouteWithChildren
  '/m/finance': typeof AuthenticatedMFinanceRouteWithChildren
  '/m/inventory': typeof AuthenticatedMInventoryRouteWithChildren
  '/m/reports': typeof AuthenticatedMReportsRoute
  '/m/sales': typeof AuthenticatedMSalesRouteWithChildren
  '/m/tax': typeof AuthenticatedMTaxRouteWithChildren
  '/m/admin/activity-logs': typeof AuthenticatedMAdminActivityLogsRoute
  '/m/admin/roles': typeof AuthenticatedMAdminRolesRoute
  '/m/admin/security': typeof AuthenticatedMAdminSecurityRoute
  '/m/admin/settings': typeof AuthenticatedMAdminSettingsRoute
  '/m/admin/users': typeof AuthenticatedMAdminUsersRoute
  '/m/compliance/calendar': typeof AuthenticatedMComplianceCalendarRoute
  '/m/compliance/licences': typeof AuthenticatedMComplianceLicencesRoute
  '/m/compliance/profile': typeof AuthenticatedMComplianceProfileRoute
  '/m/compliance/reports': typeof AuthenticatedMComplianceReportsRoute
  '/m/crm/analytics': typeof AuthenticatedMCrmAnalyticsRoute
  '/m/crm/campaigns': typeof AuthenticatedMCrmCampaignsRoute
  '/m/crm/channels': typeof AuthenticatedMCrmChannelsRoute
  '/m/crm/customers': typeof AuthenticatedMCrmCustomersRouteWithChildren
  '/m/crm/market': typeof AuthenticatedMCrmMarketRoute
  '/m/employees/attendance': typeof AuthenticatedMEmployeesAttendanceRoute
  '/m/employees/contracts': typeof AuthenticatedMEmployeesContractsRoute
  '/m/employees/departments': typeof AuthenticatedMEmployeesDepartmentsRoute
  '/m/employees/leave': typeof AuthenticatedMEmployeesLeaveRoute
  '/m/employees/payroll': typeof AuthenticatedMEmployeesPayrollRoute
  '/m/employees/payslips': typeof AuthenticatedMEmployeesPayslipsRoute
  '/m/employees/performance': typeof AuthenticatedMEmployeesPerformanceRoute
  '/m/employees/recruitment': typeof AuthenticatedMEmployeesRecruitmentRoute
  '/m/employees/staff': typeof AuthenticatedMEmployeesStaffRoute
  '/m/finance/accounts': typeof AuthenticatedMFinanceAccountsRoute
  '/m/finance/expenses': typeof AuthenticatedMFinanceExpensesRoute
  '/m/finance/payments': typeof AuthenticatedMFinancePaymentsRoute
  '/m/finance/reports': typeof AuthenticatedMFinanceReportsRoute
  '/m/finance/transfers': typeof AuthenticatedMFinanceTransfersRoute
  '/m/inventory/categories': typeof AuthenticatedMInventoryCategoriesRoute
  '/m/inventory/movements': typeof AuthenticatedMInventoryMovementsRoute
  '/m/inventory/overview': typeof AuthenticatedMInventoryOverviewRoute
  '/m/inventory/products': typeof AuthenticatedMInventoryProductsRoute
  '/m/inventory/purchases': typeof AuthenticatedMInventoryPurchasesRoute
  '/m/inventory/stock': typeof AuthenticatedMInventoryStockRoute
  '/m/inventory/suppliers': typeof AuthenticatedMInventorySuppliersRoute
  '/m/inventory/transfers': typeof AuthenticatedMInventoryTransfersRoute
  '/m/inventory/warehouses': typeof AuthenticatedMInventoryWarehousesRoute
  '/m/sales/drafts': typeof AuthenticatedMSalesDraftsRoute
  '/m/sales/history': typeof AuthenticatedMSalesHistoryRoute
  '/m/sales/invoices': typeof AuthenticatedMSalesInvoicesRoute
  '/m/sales/new': typeof AuthenticatedMSalesNewRoute
  '/m/sales/orders': typeof AuthenticatedMSalesOrdersRoute
  '/m/sales/payments': typeof AuthenticatedMSalesPaymentsRoute
  '/m/sales/quotations': typeof AuthenticatedMSalesQuotationsRoute
  '/m/sales/reports': typeof AuthenticatedMSalesReportsRoute
  '/m/sales/returns': typeof AuthenticatedMSalesReturnsRoute
  '/m/tax/assets': typeof AuthenticatedMTaxAssetsRoute
  '/m/tax/calendar': typeof AuthenticatedMTaxCalendarRoute
  '/m/tax/documents': typeof AuthenticatedMTaxDocumentsRoute
  '/m/tax/expenses': typeof AuthenticatedMTaxExpensesRoute
  '/m/tax/income': typeof AuthenticatedMTaxIncomeRoute
  '/m/tax/purchases': typeof AuthenticatedMTaxPurchasesRoute
  '/m/tax/reports': typeof AuthenticatedMTaxReportsRoute
  '/m/tax/sales': typeof AuthenticatedMTaxSalesRoute
  '/m/tax/vat': typeof AuthenticatedMTaxVatRoute
  '/m/tax/withholding': typeof AuthenticatedMTaxWithholdingRoute
  '/m/compliance': typeof AuthenticatedMComplianceIndexRoute
  '/m/crm': typeof AuthenticatedMCrmIndexRoute
  '/m/crm/customers/$id': typeof AuthenticatedMCrmCustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/m/admin': typeof AuthenticatedMAdminRouteWithChildren
  '/_authenticated/m/business-performance': typeof AuthenticatedMBusinessPerformanceRoute
  '/_authenticated/m/compliance': typeof AuthenticatedMComplianceRouteWithChildren
  '/_authenticated/m/crm': typeof AuthenticatedMCrmRouteWithChildren
  '/_authenticated/m/employees': typeof AuthenticatedMEmployeesRouteWithChildren
  '/_authenticated/m/finance': typeof AuthenticatedMFinanceRouteWithChildren
  '/_authenticated/m/inventory': typeof AuthenticatedMInventoryRouteWithChildren
  '/_authenticated/m/reports': typeof AuthenticatedMReportsRoute
  '/_authenticated/m/sales': typeof AuthenticatedMSalesRouteWithChildren
  '/_authenticated/m/tax': typeof AuthenticatedMTaxRouteWithChildren
  '/_authenticated/m/admin/activity-logs': typeof AuthenticatedMAdminActivityLogsRoute
  '/_authenticated/m/admin/roles': typeof AuthenticatedMAdminRolesRoute
  '/_authenticated/m/admin/security': typeof AuthenticatedMAdminSecurityRoute
  '/_authenticated/m/admin/settings': typeof AuthenticatedMAdminSettingsRoute
  '/_authenticated/m/admin/users': typeof AuthenticatedMAdminUsersRoute
  '/_authenticated/m/compliance/calendar': typeof AuthenticatedMComplianceCalendarRoute
  '/_authenticated/m/compliance/licences': typeof AuthenticatedMComplianceLicencesRoute
  '/_authenticated/m/compliance/profile': typeof AuthenticatedMComplianceProfileRoute
  '/_authenticated/m/compliance/reports': typeof AuthenticatedMComplianceReportsRoute
  '/_authenticated/m/crm/analytics': typeof AuthenticatedMCrmAnalyticsRoute
  '/_authenticated/m/crm/campaigns': typeof AuthenticatedMCrmCampaignsRoute
  '/_authenticated/m/crm/channels': typeof AuthenticatedMCrmChannelsRoute
  '/_authenticated/m/crm/customers': typeof AuthenticatedMCrmCustomersRouteWithChildren
  '/_authenticated/m/crm/market': typeof AuthenticatedMCrmMarketRoute
  '/_authenticated/m/employees/attendance': typeof AuthenticatedMEmployeesAttendanceRoute
  '/_authenticated/m/employees/contracts': typeof AuthenticatedMEmployeesContractsRoute
  '/_authenticated/m/employees/departments': typeof AuthenticatedMEmployeesDepartmentsRoute
  '/_authenticated/m/employees/leave': typeof AuthenticatedMEmployeesLeaveRoute
  '/_authenticated/m/employees/payroll': typeof AuthenticatedMEmployeesPayrollRoute
  '/_authenticated/m/employees/payslips': typeof AuthenticatedMEmployeesPayslipsRoute
  '/_authenticated/m/employees/performance': typeof AuthenticatedMEmployeesPerformanceRoute
  '/_authenticated/m/employees/recruitment': typeof AuthenticatedMEmployeesRecruitmentRoute
  '/_authenticated/m/employees/staff': typeof AuthenticatedMEmployeesStaffRoute
  '/_authenticated/m/finance/accounts': typeof AuthenticatedMFinanceAccountsRoute
  '/_authenticated/m/finance/expenses': typeof AuthenticatedMFinanceExpensesRoute
  '/_authenticated/m/finance/payments': typeof AuthenticatedMFinancePaymentsRoute
  '/_authenticated/m/finance/reports': typeof AuthenticatedMFinanceReportsRoute
  '/_authenticated/m/finance/transfers': typeof AuthenticatedMFinanceTransfersRoute
  '/_authenticated/m/inventory/categories': typeof AuthenticatedMInventoryCategoriesRoute
  '/_authenticated/m/inventory/movements': typeof AuthenticatedMInventoryMovementsRoute
  '/_authenticated/m/inventory/overview': typeof AuthenticatedMInventoryOverviewRoute
  '/_authenticated/m/inventory/products': typeof AuthenticatedMInventoryProductsRoute
  '/_authenticated/m/inventory/purchases': typeof AuthenticatedMInventoryPurchasesRoute
  '/_authenticated/m/inventory/stock': typeof AuthenticatedMInventoryStockRoute
  '/_authenticated/m/inventory/suppliers': typeof AuthenticatedMInventorySuppliersRoute
  '/_authenticated/m/inventory/transfers': typeof AuthenticatedMInventoryTransfersRoute
  '/_authenticated/m/inventory/warehouses': typeof AuthenticatedMInventoryWarehousesRoute
  '/_authenticated/m/sales/drafts': typeof AuthenticatedMSalesDraftsRoute
  '/_authenticated/m/sales/history': typeof AuthenticatedMSalesHistoryRoute
  '/_authenticated/m/sales/invoices': typeof AuthenticatedMSalesInvoicesRoute
  '/_authenticated/m/sales/new': typeof AuthenticatedMSalesNewRoute
  '/_authenticated/m/sales/orders': typeof AuthenticatedMSalesOrdersRoute
  '/_authenticated/m/sales/payments': typeof AuthenticatedMSalesPaymentsRoute
  '/_authenticated/m/sales/quotations': typeof AuthenticatedMSalesQuotationsRoute
  '/_authenticated/m/sales/reports': typeof AuthenticatedMSalesReportsRoute
  '/_authenticated/m/sales/returns': typeof AuthenticatedMSalesReturnsRoute
  '/_authenticated/m/tax/assets': typeof AuthenticatedMTaxAssetsRoute
  '/_authenticated/m/tax/calendar': typeof AuthenticatedMTaxCalendarRoute
  '/_authenticated/m/tax/documents': typeof AuthenticatedMTaxDocumentsRoute
  '/_authenticated/m/tax/expenses': typeof AuthenticatedMTaxExpensesRoute
  '/_authenticated/m/tax/income': typeof AuthenticatedMTaxIncomeRoute
  '/_authenticated/m/tax/purchases': typeof AuthenticatedMTaxPurchasesRoute
  '/_authenticated/m/tax/reports': typeof AuthenticatedMTaxReportsRoute
  '/_authenticated/m/tax/sales': typeof AuthenticatedMTaxSalesRoute
  '/_authenticated/m/tax/vat': typeof AuthenticatedMTaxVatRoute
  '/_authenticated/m/tax/withholding': typeof AuthenticatedMTaxWithholdingRoute
  '/_authenticated/m/compliance/': typeof AuthenticatedMComplianceIndexRoute
  '/_authenticated/m/crm/': typeof AuthenticatedMCrmIndexRoute
  '/_authenticated/m/crm/customers/$id': typeof AuthenticatedMCrmCustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/m/admin'
    | '/m/business-performance'
    | '/m/compliance'
    | '/m/crm'
    | '/m/employees'
    | '/m/finance'
    | '/m/inventory'
    | '/m/reports'
    | '/m/sales'
    | '/m/tax'
    | '/m/admin/activity-logs'
    | '/m/admin/roles'
    | '/m/admin/security'
    | '/m/admin/settings'
    | '/m/admin/users'
    | '/m/compliance/calendar'
    | '/m/compliance/licences'
    | '/m/compliance/profile'
    | '/m/compliance/reports'
    | '/m/crm/analytics'
    | '/m/crm/campaigns'
    | '/m/crm/channels'
    | '/m/crm/customers'
    | '/m/crm/market'
    | '/m/employees/attendance'
    | '/m/employees/contracts'
    | '/m/employees/departments'
    | '/m/employees/leave'
    | '/m/employees/payroll'
    | '/m/employees/payslips'
    | '/m/employees/performance'
    | '/m/employees/recruitment'
    | '/m/employees/staff'
    | '/m/finance/accounts'
    | '/m/finance/expenses'
    | '/m/finance/payments'
    | '/m/finance/reports'
    | '/m/finance/transfers'
    | '/m/inventory/categories'
    | '/m/inventory/movements'
    | '/m/inventory/overview'
    | '/m/inventory/products'
    | '/m/inventory/purchases'
    | '/m/inventory/stock'
    | '/m/inventory/suppliers'
    | '/m/inventory/transfers'
    | '/m/inventory/warehouses'
    | '/m/sales/drafts'
    | '/m/sales/history'
    | '/m/sales/invoices'
    | '/m/sales/new'
    | '/m/sales/orders'
    | '/m/sales/payments'
    | '/m/sales/quotations'
    | '/m/sales/reports'
    | '/m/sales/returns'
    | '/m/tax/assets'
    | '/m/tax/calendar'
    | '/m/tax/documents'
    | '/m/tax/expenses'
    | '/m/tax/income'
    | '/m/tax/purchases'
    | '/m/tax/reports'
    | '/m/tax/sales'
    | '/m/tax/vat'
    | '/m/tax/withholding'
    | '/m/compliance/'
    | '/m/crm/'
    | '/m/crm/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/m/admin'
    | '/m/business-performance'
    | '/m/employees'
    | '/m/finance'
    | '/m/inventory'
    | '/m/reports'
    | '/m/sales'
    | '/m/tax'
    | '/m/admin/activity-logs'
    | '/m/admin/roles'
    | '/m/admin/security'
    | '/m/admin/settings'
    | '/m/admin/users'
    | '/m/compliance/calendar'
    | '/m/compliance/licences'
    | '/m/compliance/profile'
    | '/m/compliance/reports'
    | '/m/crm/analytics'
    | '/m/crm/campaigns'
    | '/m/crm/channels'
    | '/m/crm/customers'
    | '/m/crm/market'
    | '/m/employees/attendance'
    | '/m/employees/contracts'
    | '/m/employees/departments'
    | '/m/employees/leave'
    | '/m/employees/payroll'
    | '/m/employees/payslips'
    | '/m/employees/performance'
    | '/m/employees/recruitment'
    | '/m/employees/staff'
    | '/m/finance/accounts'
    | '/m/finance/expenses'
    | '/m/finance/payments'
    | '/m/finance/reports'
    | '/m/finance/transfers'
    | '/m/inventory/categories'
    | '/m/inventory/movements'
    | '/m/inventory/overview'
    | '/m/inventory/products'
    | '/m/inventory/purchases'
    | '/m/inventory/stock'
    | '/m/inventory/suppliers'
    | '/m/inventory/transfers'
    | '/m/inventory/warehouses'
    | '/m/sales/drafts'
    | '/m/sales/history'
    | '/m/sales/invoices'
    | '/m/sales/new'
    | '/m/sales/orders'
    | '/m/sales/payments'
    | '/m/sales/quotations'
    | '/m/sales/reports'
    | '/m/sales/returns'
    | '/m/tax/assets'
    | '/m/tax/calendar'
    | '/m/tax/documents'
    | '/m/tax/expenses'
    | '/m/tax/income'
    | '/m/tax/purchases'
    | '/m/tax/reports'
    | '/m/tax/sales'
    | '/m/tax/vat'
    | '/m/tax/withholding'
    | '/m/compliance'
    | '/m/crm'
    | '/m/crm/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/m/admin'
    | '/_authenticated/m/business-performance'
    | '/_authenticated/m/compliance'
    | '/_authenticated/m/crm'
    | '/_authenticated/m/employees'
    | '/_authenticated/m/finance'
    | '/_authenticated/m/inventory'
    | '/_authenticated/m/reports'
    | '/_authenticated/m/sales'
    | '/_authenticated/m/tax'
    | '/_authenticated/m/admin/activity-logs'
    | '/_authenticated/m/admin/roles'
    | '/_authenticated/m/admin/security'
    | '/_authenticated/m/admin/settings'
    | '/_authenticated/m/admin/users'
    | '/_authenticated/m/compliance/calendar'
    | '/_authenticated/m/compliance/licences'
    | '/_authenticated/m/compliance/profile'
    | '/_authenticated/m/compliance/reports'
    | '/_authenticated/m/crm/analytics'
    | '/_authenticated/m/crm/campaigns'
    | '/_authenticated/m/crm/channels'
    | '/_authenticated/m/crm/customers'
    | '/_authenticated/m/crm/market'
    | '/_authenticated/m/employees/attendance'
    | '/_authenticated/m/employees/contracts'
    | '/_authenticated/m/employees/departments'
    | '/_authenticated/m/employees/leave'
    | '/_authenticated/m/employees/payroll'
    | '/_authenticated/m/employees/payslips'
    | '/_authenticated/m/employees/performance'
    | '/_authenticated/m/employees/recruitment'
    | '/_authenticated/m/employees/staff'
    | '/_authenticated/m/finance/accounts'
    | '/_authenticated/m/finance/expenses'
    | '/_authenticated/m/finance/payments'
    | '/_authenticated/m/finance/reports'
    | '/_authenticated/m/finance/transfers'
    | '/_authenticated/m/inventory/categories'
    | '/_authenticated/m/inventory/movements'
    | '/_authenticated/m/inventory/overview'
    | '/_authenticated/m/inventory/products'
    | '/_authenticated/m/inventory/purchases'
    | '/_authenticated/m/inventory/stock'
    | '/_authenticated/m/inventory/suppliers'
    | '/_authenticated/m/inventory/transfers'
    | '/_authenticated/m/inventory/warehouses'
    | '/_authenticated/m/sales/drafts'
    | '/_authenticated/m/sales/history'
    | '/_authenticated/m/sales/invoices'
    | '/_authenticated/m/sales/new'
    | '/_authenticated/m/sales/orders'
    | '/_authenticated/m/sales/payments'
    | '/_authenticated/m/sales/quotations'
    | '/_authenticated/m/sales/reports'
    | '/_authenticated/m/sales/returns'
    | '/_authenticated/m/tax/assets'
    | '/_authenticated/m/tax/calendar'
    | '/_authenticated/m/tax/documents'
    | '/_authenticated/m/tax/expenses'
    | '/_authenticated/m/tax/income'
    | '/_authenticated/m/tax/purchases'
    | '/_authenticated/m/tax/reports'
    | '/_authenticated/m/tax/sales'
    | '/_authenticated/m/tax/vat'
    | '/_authenticated/m/tax/withholding'
    | '/_authenticated/m/compliance/'
    | '/_authenticated/m/crm/'
    | '/_authenticated/m/crm/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/tax': {
      id: '/_authenticated/m/tax'
      path: '/m/tax'
      fullPath: '/m/tax'
      preLoaderRoute: typeof AuthenticatedMTaxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/sales': {
      id: '/_authenticated/m/sales'
      path: '/m/sales'
      fullPath: '/m/sales'
      preLoaderRoute: typeof AuthenticatedMSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/reports': {
      id: '/_authenticated/m/reports'
      path: '/m/reports'
      fullPath: '/m/reports'
      preLoaderRoute: typeof AuthenticatedMReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/inventory': {
      id: '/_authenticated/m/inventory'
      path: '/m/inventory'
      fullPath: '/m/inventory'
      preLoaderRoute: typeof AuthenticatedMInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/finance': {
      id: '/_authenticated/m/finance'
      path: '/m/finance'
      fullPath: '/m/finance'
      preLoaderRoute: typeof AuthenticatedMFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/employees': {
      id: '/_authenticated/m/employees'
      path: '/m/employees'
      fullPath: '/m/employees'
      preLoaderRoute: typeof AuthenticatedMEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/crm': {
      id: '/_authenticated/m/crm'
      path: '/m/crm'
      fullPath: '/m/crm'
      preLoaderRoute: typeof AuthenticatedMCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/compliance': {
      id: '/_authenticated/m/compliance'
      path: '/m/compliance'
      fullPath: '/m/compliance'
      preLoaderRoute: typeof AuthenticatedMComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/business-performance': {
      id: '/_authenticated/m/business-performance'
      path: '/m/business-performance'
      fullPath: '/m/business-performance'
      preLoaderRoute: typeof AuthenticatedMBusinessPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/admin': {
      id: '/_authenticated/m/admin'
      path: '/m/admin'
      fullPath: '/m/admin'
      preLoaderRoute: typeof AuthenticatedMAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/crm/': {
      id: '/_authenticated/m/crm/'
      path: '/'
      fullPath: '/m/crm/'
      preLoaderRoute: typeof AuthenticatedMCrmIndexRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/compliance/': {
      id: '/_authenticated/m/compliance/'
      path: '/'
      fullPath: '/m/compliance/'
      preLoaderRoute: typeof AuthenticatedMComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedMComplianceRoute
    }
    '/_authenticated/m/tax/withholding': {
      id: '/_authenticated/m/tax/withholding'
      path: '/withholding'
      fullPath: '/m/tax/withholding'
      preLoaderRoute: typeof AuthenticatedMTaxWithholdingRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/vat': {
      id: '/_authenticated/m/tax/vat'
      path: '/vat'
      fullPath: '/m/tax/vat'
      preLoaderRoute: typeof AuthenticatedMTaxVatRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/sales': {
      id: '/_authenticated/m/tax/sales'
      path: '/sales'
      fullPath: '/m/tax/sales'
      preLoaderRoute: typeof AuthenticatedMTaxSalesRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/reports': {
      id: '/_authenticated/m/tax/reports'
      path: '/reports'
      fullPath: '/m/tax/reports'
      preLoaderRoute: typeof AuthenticatedMTaxReportsRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/purchases': {
      id: '/_authenticated/m/tax/purchases'
      path: '/purchases'
      fullPath: '/m/tax/purchases'
      preLoaderRoute: typeof AuthenticatedMTaxPurchasesRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/income': {
      id: '/_authenticated/m/tax/income'
      path: '/income'
      fullPath: '/m/tax/income'
      preLoaderRoute: typeof AuthenticatedMTaxIncomeRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/expenses': {
      id: '/_authenticated/m/tax/expenses'
      path: '/expenses'
      fullPath: '/m/tax/expenses'
      preLoaderRoute: typeof AuthenticatedMTaxExpensesRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/documents': {
      id: '/_authenticated/m/tax/documents'
      path: '/documents'
      fullPath: '/m/tax/documents'
      preLoaderRoute: typeof AuthenticatedMTaxDocumentsRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/calendar': {
      id: '/_authenticated/m/tax/calendar'
      path: '/calendar'
      fullPath: '/m/tax/calendar'
      preLoaderRoute: typeof AuthenticatedMTaxCalendarRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/tax/assets': {
      id: '/_authenticated/m/tax/assets'
      path: '/assets'
      fullPath: '/m/tax/assets'
      preLoaderRoute: typeof AuthenticatedMTaxAssetsRouteImport
      parentRoute: typeof AuthenticatedMTaxRoute
    }
    '/_authenticated/m/sales/returns': {
      id: '/_authenticated/m/sales/returns'
      path: '/returns'
      fullPath: '/m/sales/returns'
      preLoaderRoute: typeof AuthenticatedMSalesReturnsRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/sales/reports': {
      id: '/_authenticated/m/sales/reports'
      path: '/reports'
      fullPath: '/m/sales/reports'
      preLoaderRoute: typeof AuthenticatedMSalesReportsRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/sales/quotations': {
      id: '/_authenticated/m/sales/quotations'
      path: '/quotations'
      fullPath: '/m/sales/quotations'
      preLoaderRoute: typeof AuthenticatedMSalesQuotationsRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/sales/payments': {
      id: '/_authenticated/m/sales/payments'
      path: '/payments'
      fullPath: '/m/sales/payments'
      preLoaderRoute: typeof AuthenticatedMSalesPaymentsRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/sales/orders': {
      id: '/_authenticated/m/sales/orders'
      path: '/orders'
      fullPath: '/m/sales/orders'
      preLoaderRoute: typeof AuthenticatedMSalesOrdersRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/sales/new': {
      id: '/_authenticated/m/sales/new'
      path: '/new'
      fullPath: '/m/sales/new'
      preLoaderRoute: typeof AuthenticatedMSalesNewRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/sales/invoices': {
      id: '/_authenticated/m/sales/invoices'
      path: '/invoices'
      fullPath: '/m/sales/invoices'
      preLoaderRoute: typeof AuthenticatedMSalesInvoicesRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/sales/history': {
      id: '/_authenticated/m/sales/history'
      path: '/history'
      fullPath: '/m/sales/history'
      preLoaderRoute: typeof AuthenticatedMSalesHistoryRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/sales/drafts': {
      id: '/_authenticated/m/sales/drafts'
      path: '/drafts'
      fullPath: '/m/sales/drafts'
      preLoaderRoute: typeof AuthenticatedMSalesDraftsRouteImport
      parentRoute: typeof AuthenticatedMSalesRoute
    }
    '/_authenticated/m/inventory/warehouses': {
      id: '/_authenticated/m/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/m/inventory/warehouses'
      preLoaderRoute: typeof AuthenticatedMInventoryWarehousesRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/inventory/transfers': {
      id: '/_authenticated/m/inventory/transfers'
      path: '/transfers'
      fullPath: '/m/inventory/transfers'
      preLoaderRoute: typeof AuthenticatedMInventoryTransfersRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/inventory/suppliers': {
      id: '/_authenticated/m/inventory/suppliers'
      path: '/suppliers'
      fullPath: '/m/inventory/suppliers'
      preLoaderRoute: typeof AuthenticatedMInventorySuppliersRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/inventory/stock': {
      id: '/_authenticated/m/inventory/stock'
      path: '/stock'
      fullPath: '/m/inventory/stock'
      preLoaderRoute: typeof AuthenticatedMInventoryStockRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/inventory/purchases': {
      id: '/_authenticated/m/inventory/purchases'
      path: '/purchases'
      fullPath: '/m/inventory/purchases'
      preLoaderRoute: typeof AuthenticatedMInventoryPurchasesRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/inventory/products': {
      id: '/_authenticated/m/inventory/products'
      path: '/products'
      fullPath: '/m/inventory/products'
      preLoaderRoute: typeof AuthenticatedMInventoryProductsRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/inventory/overview': {
      id: '/_authenticated/m/inventory/overview'
      path: '/overview'
      fullPath: '/m/inventory/overview'
      preLoaderRoute: typeof AuthenticatedMInventoryOverviewRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/inventory/movements': {
      id: '/_authenticated/m/inventory/movements'
      path: '/movements'
      fullPath: '/m/inventory/movements'
      preLoaderRoute: typeof AuthenticatedMInventoryMovementsRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/inventory/categories': {
      id: '/_authenticated/m/inventory/categories'
      path: '/categories'
      fullPath: '/m/inventory/categories'
      preLoaderRoute: typeof AuthenticatedMInventoryCategoriesRouteImport
      parentRoute: typeof AuthenticatedMInventoryRoute
    }
    '/_authenticated/m/finance/transfers': {
      id: '/_authenticated/m/finance/transfers'
      path: '/transfers'
      fullPath: '/m/finance/transfers'
      preLoaderRoute: typeof AuthenticatedMFinanceTransfersRouteImport
      parentRoute: typeof AuthenticatedMFinanceRoute
    }
    '/_authenticated/m/finance/reports': {
      id: '/_authenticated/m/finance/reports'
      path: '/reports'
      fullPath: '/m/finance/reports'
      preLoaderRoute: typeof AuthenticatedMFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedMFinanceRoute
    }
    '/_authenticated/m/finance/payments': {
      id: '/_authenticated/m/finance/payments'
      path: '/payments'
      fullPath: '/m/finance/payments'
      preLoaderRoute: typeof AuthenticatedMFinancePaymentsRouteImport
      parentRoute: typeof AuthenticatedMFinanceRoute
    }
    '/_authenticated/m/finance/expenses': {
      id: '/_authenticated/m/finance/expenses'
      path: '/expenses'
      fullPath: '/m/finance/expenses'
      preLoaderRoute: typeof AuthenticatedMFinanceExpensesRouteImport
      parentRoute: typeof AuthenticatedMFinanceRoute
    }
    '/_authenticated/m/finance/accounts': {
      id: '/_authenticated/m/finance/accounts'
      path: '/accounts'
      fullPath: '/m/finance/accounts'
      preLoaderRoute: typeof AuthenticatedMFinanceAccountsRouteImport
      parentRoute: typeof AuthenticatedMFinanceRoute
    }
    '/_authenticated/m/employees/staff': {
      id: '/_authenticated/m/employees/staff'
      path: '/staff'
      fullPath: '/m/employees/staff'
      preLoaderRoute: typeof AuthenticatedMEmployeesStaffRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/employees/recruitment': {
      id: '/_authenticated/m/employees/recruitment'
      path: '/recruitment'
      fullPath: '/m/employees/recruitment'
      preLoaderRoute: typeof AuthenticatedMEmployeesRecruitmentRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/employees/performance': {
      id: '/_authenticated/m/employees/performance'
      path: '/performance'
      fullPath: '/m/employees/performance'
      preLoaderRoute: typeof AuthenticatedMEmployeesPerformanceRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/employees/payslips': {
      id: '/_authenticated/m/employees/payslips'
      path: '/payslips'
      fullPath: '/m/employees/payslips'
      preLoaderRoute: typeof AuthenticatedMEmployeesPayslipsRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/employees/payroll': {
      id: '/_authenticated/m/employees/payroll'
      path: '/payroll'
      fullPath: '/m/employees/payroll'
      preLoaderRoute: typeof AuthenticatedMEmployeesPayrollRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/employees/leave': {
      id: '/_authenticated/m/employees/leave'
      path: '/leave'
      fullPath: '/m/employees/leave'
      preLoaderRoute: typeof AuthenticatedMEmployeesLeaveRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/employees/departments': {
      id: '/_authenticated/m/employees/departments'
      path: '/departments'
      fullPath: '/m/employees/departments'
      preLoaderRoute: typeof AuthenticatedMEmployeesDepartmentsRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/employees/contracts': {
      id: '/_authenticated/m/employees/contracts'
      path: '/contracts'
      fullPath: '/m/employees/contracts'
      preLoaderRoute: typeof AuthenticatedMEmployeesContractsRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/employees/attendance': {
      id: '/_authenticated/m/employees/attendance'
      path: '/attendance'
      fullPath: '/m/employees/attendance'
      preLoaderRoute: typeof AuthenticatedMEmployeesAttendanceRouteImport
      parentRoute: typeof AuthenticatedMEmployeesRoute
    }
    '/_authenticated/m/crm/market': {
      id: '/_authenticated/m/crm/market'
      path: '/market'
      fullPath: '/m/crm/market'
      preLoaderRoute: typeof AuthenticatedMCrmMarketRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/customers': {
      id: '/_authenticated/m/crm/customers'
      path: '/customers'
      fullPath: '/m/crm/customers'
      preLoaderRoute: typeof AuthenticatedMCrmCustomersRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/channels': {
      id: '/_authenticated/m/crm/channels'
      path: '/channels'
      fullPath: '/m/crm/channels'
      preLoaderRoute: typeof AuthenticatedMCrmChannelsRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/campaigns': {
      id: '/_authenticated/m/crm/campaigns'
      path: '/campaigns'
      fullPath: '/m/crm/campaigns'
      preLoaderRoute: typeof AuthenticatedMCrmCampaignsRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/crm/analytics': {
      id: '/_authenticated/m/crm/analytics'
      path: '/analytics'
      fullPath: '/m/crm/analytics'
      preLoaderRoute: typeof AuthenticatedMCrmAnalyticsRouteImport
      parentRoute: typeof AuthenticatedMCrmRoute
    }
    '/_authenticated/m/compliance/reports': {
      id: '/_authenticated/m/compliance/reports'
      path: '/reports'
      fullPath: '/m/compliance/reports'
      preLoaderRoute: typeof AuthenticatedMComplianceReportsRouteImport
      parentRoute: typeof AuthenticatedMComplianceRoute
    }
    '/_authenticated/m/compliance/profile': {
      id: '/_authenticated/m/compliance/profile'
      path: '/profile'
      fullPath: '/m/compliance/profile'
      preLoaderRoute: typeof AuthenticatedMComplianceProfileRouteImport
      parentRoute: typeof AuthenticatedMComplianceRoute
    }
    '/_authenticated/m/compliance/licences': {
      id: '/_authenticated/m/compliance/licences'
      path: '/licences'
      fullPath: '/m/compliance/licences'
      preLoaderRoute: typeof AuthenticatedMComplianceLicencesRouteImport
      parentRoute: typeof AuthenticatedMComplianceRoute
    }
    '/_authenticated/m/compliance/calendar': {
      id: '/_authenticated/m/compliance/calendar'
      path: '/calendar'
      fullPath: '/m/compliance/calendar'
      preLoaderRoute: typeof AuthenticatedMComplianceCalendarRouteImport
      parentRoute: typeof AuthenticatedMComplianceRoute
    }
    '/_authenticated/m/admin/users': {
      id: '/_authenticated/m/admin/users'
      path: '/users'
      fullPath: '/m/admin/users'
      preLoaderRoute: typeof AuthenticatedMAdminUsersRouteImport
      parentRoute: typeof AuthenticatedMAdminRoute
    }
    '/_authenticated/m/admin/settings': {
      id: '/_authenticated/m/admin/settings'
      path: '/settings'
      fullPath: '/m/admin/settings'
      preLoaderRoute: typeof AuthenticatedMAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedMAdminRoute
    }
    '/_authenticated/m/admin/security': {
      id: '/_authenticated/m/admin/security'
      path: '/security'
      fullPath: '/m/admin/security'
      preLoaderRoute: typeof AuthenticatedMAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedMAdminRoute
    }
    '/_authenticated/m/admin/roles': {
      id: '/_authenticated/m/admin/roles'
      path: '/roles'
      fullPath: '/m/admin/roles'
      preLoaderRoute: typeof AuthenticatedMAdminRolesRouteImport
      parentRoute: typeof AuthenticatedMAdminRoute
    }
    '/_authenticated/m/admin/activity-logs': {
      id: '/_authenticated/m/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/m/admin/activity-logs'
      preLoaderRoute: typeof AuthenticatedMAdminActivityLogsRouteImport
      parentRoute: typeof AuthenticatedMAdminRoute
    }
    '/_authenticated/m/crm/customers/$id': {
      id: '/_authenticated/m/crm/customers/$id'
      path: '/$id'
      fullPath: '/m/crm/customers/$id'
      preLoaderRoute: typeof AuthenticatedMCrmCustomersIdRouteImport
      parentRoute: typeof AuthenticatedMCrmCustomersRoute
    }
  }
}

interface AuthenticatedMAdminRouteChildren {
  AuthenticatedMAdminActivityLogsRoute: typeof AuthenticatedMAdminActivityLogsRoute
  AuthenticatedMAdminRolesRoute: typeof AuthenticatedMAdminRolesRoute
  AuthenticatedMAdminSecurityRoute: typeof AuthenticatedMAdminSecurityRoute
  AuthenticatedMAdminSettingsRoute: typeof AuthenticatedMAdminSettingsRoute
  AuthenticatedMAdminUsersRoute: typeof AuthenticatedMAdminUsersRoute
}

const AuthenticatedMAdminRouteChildren: AuthenticatedMAdminRouteChildren = {
  AuthenticatedMAdminActivityLogsRoute: AuthenticatedMAdminActivityLogsRoute,
  AuthenticatedMAdminRolesRoute: AuthenticatedMAdminRolesRoute,
  AuthenticatedMAdminSecurityRoute: AuthenticatedMAdminSecurityRoute,
  AuthenticatedMAdminSettingsRoute: AuthenticatedMAdminSettingsRoute,
  AuthenticatedMAdminUsersRoute: AuthenticatedMAdminUsersRoute,
}

const AuthenticatedMAdminRouteWithChildren =
  AuthenticatedMAdminRoute._addFileChildren(AuthenticatedMAdminRouteChildren)

interface AuthenticatedMComplianceRouteChildren {
  AuthenticatedMComplianceCalendarRoute: typeof AuthenticatedMComplianceCalendarRoute
  AuthenticatedMComplianceLicencesRoute: typeof AuthenticatedMComplianceLicencesRoute
  AuthenticatedMComplianceProfileRoute: typeof AuthenticatedMComplianceProfileRoute
  AuthenticatedMComplianceReportsRoute: typeof AuthenticatedMComplianceReportsRoute
  AuthenticatedMComplianceIndexRoute: typeof AuthenticatedMComplianceIndexRoute
}

const AuthenticatedMComplianceRouteChildren: AuthenticatedMComplianceRouteChildren =
  {
    AuthenticatedMComplianceCalendarRoute:
      AuthenticatedMComplianceCalendarRoute,
    AuthenticatedMComplianceLicencesRoute:
      AuthenticatedMComplianceLicencesRoute,
    AuthenticatedMComplianceProfileRoute: AuthenticatedMComplianceProfileRoute,
    AuthenticatedMComplianceReportsRoute: AuthenticatedMComplianceReportsRoute,
    AuthenticatedMComplianceIndexRoute: AuthenticatedMComplianceIndexRoute,
  }

const AuthenticatedMComplianceRouteWithChildren =
  AuthenticatedMComplianceRoute._addFileChildren(
    AuthenticatedMComplianceRouteChildren,
  )

interface AuthenticatedMCrmCustomersRouteChildren {
  AuthenticatedMCrmCustomersIdRoute: typeof AuthenticatedMCrmCustomersIdRoute
}

const AuthenticatedMCrmCustomersRouteChildren: AuthenticatedMCrmCustomersRouteChildren =
  {
    AuthenticatedMCrmCustomersIdRoute: AuthenticatedMCrmCustomersIdRoute,
  }

const AuthenticatedMCrmCustomersRouteWithChildren =
  AuthenticatedMCrmCustomersRoute._addFileChildren(
    AuthenticatedMCrmCustomersRouteChildren,
  )

interface AuthenticatedMCrmRouteChildren {
  AuthenticatedMCrmAnalyticsRoute: typeof AuthenticatedMCrmAnalyticsRoute
  AuthenticatedMCrmCampaignsRoute: typeof AuthenticatedMCrmCampaignsRoute
  AuthenticatedMCrmChannelsRoute: typeof AuthenticatedMCrmChannelsRoute
  AuthenticatedMCrmCustomersRoute: typeof AuthenticatedMCrmCustomersRouteWithChildren
  AuthenticatedMCrmMarketRoute: typeof AuthenticatedMCrmMarketRoute
  AuthenticatedMCrmIndexRoute: typeof AuthenticatedMCrmIndexRoute
}

const AuthenticatedMCrmRouteChildren: AuthenticatedMCrmRouteChildren = {
  AuthenticatedMCrmAnalyticsRoute: AuthenticatedMCrmAnalyticsRoute,
  AuthenticatedMCrmCampaignsRoute: AuthenticatedMCrmCampaignsRoute,
  AuthenticatedMCrmChannelsRoute: AuthenticatedMCrmChannelsRoute,
  AuthenticatedMCrmCustomersRoute: AuthenticatedMCrmCustomersRouteWithChildren,
  AuthenticatedMCrmMarketRoute: AuthenticatedMCrmMarketRoute,
  AuthenticatedMCrmIndexRoute: AuthenticatedMCrmIndexRoute,
}

const AuthenticatedMCrmRouteWithChildren =
  AuthenticatedMCrmRoute._addFileChildren(AuthenticatedMCrmRouteChildren)

interface AuthenticatedMEmployeesRouteChildren {
  AuthenticatedMEmployeesAttendanceRoute: typeof AuthenticatedMEmployeesAttendanceRoute
  AuthenticatedMEmployeesContractsRoute: typeof AuthenticatedMEmployeesContractsRoute
  AuthenticatedMEmployeesDepartmentsRoute: typeof AuthenticatedMEmployeesDepartmentsRoute
  AuthenticatedMEmployeesLeaveRoute: typeof AuthenticatedMEmployeesLeaveRoute
  AuthenticatedMEmployeesPayrollRoute: typeof AuthenticatedMEmployeesPayrollRoute
  AuthenticatedMEmployeesPayslipsRoute: typeof AuthenticatedMEmployeesPayslipsRoute
  AuthenticatedMEmployeesPerformanceRoute: typeof AuthenticatedMEmployeesPerformanceRoute
  AuthenticatedMEmployeesRecruitmentRoute: typeof AuthenticatedMEmployeesRecruitmentRoute
  AuthenticatedMEmployeesStaffRoute: typeof AuthenticatedMEmployeesStaffRoute
}

const AuthenticatedMEmployeesRouteChildren: AuthenticatedMEmployeesRouteChildren =
  {
    AuthenticatedMEmployeesAttendanceRoute:
      AuthenticatedMEmployeesAttendanceRoute,
    AuthenticatedMEmployeesContractsRoute:
      AuthenticatedMEmployeesContractsRoute,
    AuthenticatedMEmployeesDepartmentsRoute:
      AuthenticatedMEmployeesDepartmentsRoute,
    AuthenticatedMEmployeesLeaveRoute: AuthenticatedMEmployeesLeaveRoute,
    AuthenticatedMEmployeesPayrollRoute: AuthenticatedMEmployeesPayrollRoute,
    AuthenticatedMEmployeesPayslipsRoute: AuthenticatedMEmployeesPayslipsRoute,
    AuthenticatedMEmployeesPerformanceRoute:
      AuthenticatedMEmployeesPerformanceRoute,
    AuthenticatedMEmployeesRecruitmentRoute:
      AuthenticatedMEmployeesRecruitmentRoute,
    AuthenticatedMEmployeesStaffRoute: AuthenticatedMEmployeesStaffRoute,
  }

const AuthenticatedMEmployeesRouteWithChildren =
  AuthenticatedMEmployeesRoute._addFileChildren(
    AuthenticatedMEmployeesRouteChildren,
  )

interface AuthenticatedMFinanceRouteChildren {
  AuthenticatedMFinanceAccountsRoute: typeof AuthenticatedMFinanceAccountsRoute
  AuthenticatedMFinanceExpensesRoute: typeof AuthenticatedMFinanceExpensesRoute
  AuthenticatedMFinancePaymentsRoute: typeof AuthenticatedMFinancePaymentsRoute
  AuthenticatedMFinanceReportsRoute: typeof AuthenticatedMFinanceReportsRoute
  AuthenticatedMFinanceTransfersRoute: typeof AuthenticatedMFinanceTransfersRoute
}

const AuthenticatedMFinanceRouteChildren: AuthenticatedMFinanceRouteChildren = {
  AuthenticatedMFinanceAccountsRoute: AuthenticatedMFinanceAccountsRoute,
  AuthenticatedMFinanceExpensesRoute: AuthenticatedMFinanceExpensesRoute,
  AuthenticatedMFinancePaymentsRoute: AuthenticatedMFinancePaymentsRoute,
  AuthenticatedMFinanceReportsRoute: AuthenticatedMFinanceReportsRoute,
  AuthenticatedMFinanceTransfersRoute: AuthenticatedMFinanceTransfersRoute,
}

const AuthenticatedMFinanceRouteWithChildren =
  AuthenticatedMFinanceRoute._addFileChildren(
    AuthenticatedMFinanceRouteChildren,
  )

interface AuthenticatedMInventoryRouteChildren {
  AuthenticatedMInventoryCategoriesRoute: typeof AuthenticatedMInventoryCategoriesRoute
  AuthenticatedMInventoryMovementsRoute: typeof AuthenticatedMInventoryMovementsRoute
  AuthenticatedMInventoryOverviewRoute: typeof AuthenticatedMInventoryOverviewRoute
  AuthenticatedMInventoryProductsRoute: typeof AuthenticatedMInventoryProductsRoute
  AuthenticatedMInventoryPurchasesRoute: typeof AuthenticatedMInventoryPurchasesRoute
  AuthenticatedMInventoryStockRoute: typeof AuthenticatedMInventoryStockRoute
  AuthenticatedMInventorySuppliersRoute: typeof AuthenticatedMInventorySuppliersRoute
  AuthenticatedMInventoryTransfersRoute: typeof AuthenticatedMInventoryTransfersRoute
  AuthenticatedMInventoryWarehousesRoute: typeof AuthenticatedMInventoryWarehousesRoute
}

const AuthenticatedMInventoryRouteChildren: AuthenticatedMInventoryRouteChildren =
  {
    AuthenticatedMInventoryCategoriesRoute:
      AuthenticatedMInventoryCategoriesRoute,
    AuthenticatedMInventoryMovementsRoute:
      AuthenticatedMInventoryMovementsRoute,
    AuthenticatedMInventoryOverviewRoute: AuthenticatedMInventoryOverviewRoute,
    AuthenticatedMInventoryProductsRoute: AuthenticatedMInventoryProductsRoute,
    AuthenticatedMInventoryPurchasesRoute:
      AuthenticatedMInventoryPurchasesRoute,
    AuthenticatedMInventoryStockRoute: AuthenticatedMInventoryStockRoute,
    AuthenticatedMInventorySuppliersRoute:
      AuthenticatedMInventorySuppliersRoute,
    AuthenticatedMInventoryTransfersRoute:
      AuthenticatedMInventoryTransfersRoute,
    AuthenticatedMInventoryWarehousesRoute:
      AuthenticatedMInventoryWarehousesRoute,
  }

const AuthenticatedMInventoryRouteWithChildren =
  AuthenticatedMInventoryRoute._addFileChildren(
    AuthenticatedMInventoryRouteChildren,
  )

interface AuthenticatedMSalesRouteChildren {
  AuthenticatedMSalesDraftsRoute: typeof AuthenticatedMSalesDraftsRoute
  AuthenticatedMSalesHistoryRoute: typeof AuthenticatedMSalesHistoryRoute
  AuthenticatedMSalesInvoicesRoute: typeof AuthenticatedMSalesInvoicesRoute
  AuthenticatedMSalesNewRoute: typeof AuthenticatedMSalesNewRoute
  AuthenticatedMSalesOrdersRoute: typeof AuthenticatedMSalesOrdersRoute
  AuthenticatedMSalesPaymentsRoute: typeof AuthenticatedMSalesPaymentsRoute
  AuthenticatedMSalesQuotationsRoute: typeof AuthenticatedMSalesQuotationsRoute
  AuthenticatedMSalesReportsRoute: typeof AuthenticatedMSalesReportsRoute
  AuthenticatedMSalesReturnsRoute: typeof AuthenticatedMSalesReturnsRoute
}

const AuthenticatedMSalesRouteChildren: AuthenticatedMSalesRouteChildren = {
  AuthenticatedMSalesDraftsRoute: AuthenticatedMSalesDraftsRoute,
  AuthenticatedMSalesHistoryRoute: AuthenticatedMSalesHistoryRoute,
  AuthenticatedMSalesInvoicesRoute: AuthenticatedMSalesInvoicesRoute,
  AuthenticatedMSalesNewRoute: AuthenticatedMSalesNewRoute,
  AuthenticatedMSalesOrdersRoute: AuthenticatedMSalesOrdersRoute,
  AuthenticatedMSalesPaymentsRoute: AuthenticatedMSalesPaymentsRoute,
  AuthenticatedMSalesQuotationsRoute: AuthenticatedMSalesQuotationsRoute,
  AuthenticatedMSalesReportsRoute: AuthenticatedMSalesReportsRoute,
  AuthenticatedMSalesReturnsRoute: AuthenticatedMSalesReturnsRoute,
}

const AuthenticatedMSalesRouteWithChildren =
  AuthenticatedMSalesRoute._addFileChildren(AuthenticatedMSalesRouteChildren)

interface AuthenticatedMTaxRouteChildren {
  AuthenticatedMTaxAssetsRoute: typeof AuthenticatedMTaxAssetsRoute
  AuthenticatedMTaxCalendarRoute: typeof AuthenticatedMTaxCalendarRoute
  AuthenticatedMTaxDocumentsRoute: typeof AuthenticatedMTaxDocumentsRoute
  AuthenticatedMTaxExpensesRoute: typeof AuthenticatedMTaxExpensesRoute
  AuthenticatedMTaxIncomeRoute: typeof AuthenticatedMTaxIncomeRoute
  AuthenticatedMTaxPurchasesRoute: typeof AuthenticatedMTaxPurchasesRoute
  AuthenticatedMTaxReportsRoute: typeof AuthenticatedMTaxReportsRoute
  AuthenticatedMTaxSalesRoute: typeof AuthenticatedMTaxSalesRoute
  AuthenticatedMTaxVatRoute: typeof AuthenticatedMTaxVatRoute
  AuthenticatedMTaxWithholdingRoute: typeof AuthenticatedMTaxWithholdingRoute
}

const AuthenticatedMTaxRouteChildren: AuthenticatedMTaxRouteChildren = {
  AuthenticatedMTaxAssetsRoute: AuthenticatedMTaxAssetsRoute,
  AuthenticatedMTaxCalendarRoute: AuthenticatedMTaxCalendarRoute,
  AuthenticatedMTaxDocumentsRoute: AuthenticatedMTaxDocumentsRoute,
  AuthenticatedMTaxExpensesRoute: AuthenticatedMTaxExpensesRoute,
  AuthenticatedMTaxIncomeRoute: AuthenticatedMTaxIncomeRoute,
  AuthenticatedMTaxPurchasesRoute: AuthenticatedMTaxPurchasesRoute,
  AuthenticatedMTaxReportsRoute: AuthenticatedMTaxReportsRoute,
  AuthenticatedMTaxSalesRoute: AuthenticatedMTaxSalesRoute,
  AuthenticatedMTaxVatRoute: AuthenticatedMTaxVatRoute,
  AuthenticatedMTaxWithholdingRoute: AuthenticatedMTaxWithholdingRoute,
}

const AuthenticatedMTaxRouteWithChildren =
  AuthenticatedMTaxRoute._addFileChildren(AuthenticatedMTaxRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMAdminRoute: typeof AuthenticatedMAdminRouteWithChildren
  AuthenticatedMBusinessPerformanceRoute: typeof AuthenticatedMBusinessPerformanceRoute
  AuthenticatedMComplianceRoute: typeof AuthenticatedMComplianceRouteWithChildren
  AuthenticatedMCrmRoute: typeof AuthenticatedMCrmRouteWithChildren
  AuthenticatedMEmployeesRoute: typeof AuthenticatedMEmployeesRouteWithChildren
  AuthenticatedMFinanceRoute: typeof AuthenticatedMFinanceRouteWithChildren
  AuthenticatedMInventoryRoute: typeof AuthenticatedMInventoryRouteWithChildren
  AuthenticatedMReportsRoute: typeof AuthenticatedMReportsRoute
  AuthenticatedMSalesRoute: typeof AuthenticatedMSalesRouteWithChildren
  AuthenticatedMTaxRoute: typeof AuthenticatedMTaxRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMAdminRoute: AuthenticatedMAdminRouteWithChildren,
  AuthenticatedMBusinessPerformanceRoute:
    AuthenticatedMBusinessPerformanceRoute,
  AuthenticatedMComplianceRoute: AuthenticatedMComplianceRouteWithChildren,
  AuthenticatedMCrmRoute: AuthenticatedMCrmRouteWithChildren,
  AuthenticatedMEmployeesRoute: AuthenticatedMEmployeesRouteWithChildren,
  AuthenticatedMFinanceRoute: AuthenticatedMFinanceRouteWithChildren,
  AuthenticatedMInventoryRoute: AuthenticatedMInventoryRouteWithChildren,
  AuthenticatedMReportsRoute: AuthenticatedMReportsRoute,
  AuthenticatedMSalesRoute: AuthenticatedMSalesRouteWithChildren,
  AuthenticatedMTaxRoute: AuthenticatedMTaxRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
